language: python
python:
  - "2.7"

install:
  - cp -r pasty_server.conf.EXAMPLE pasty_server.conf
  - pip install -r requirements.txt

script:
  - coverage run setup.py test

after_success:
  - coveralls
